services:
  activemq:
    image: apache/activemq-classic:5.17.7
    container_name: active-mq
    environment:
      ACTIVEMQ_WEB_USER: admin
      ACTIVEMQ_WEB_PASSWORD: admin
    ports:
      - "61616:61616"  # JMS
      - "8161:8161"    # Web console
    volumes:
      - activemq-data:/opt/activemq/data  # persistent data
    networks:
      - activemq-network
    restart: unless-stopped

networks:
  activemq-network:

volumes:
  activemq-data: