spring:
  application:
    name: notification
  data:
    mongodb:
      uri: mongodb://localhost:27017/eureka-db
      database: eureka-db
  cloud:
    discovery:
      enabled: true

logging:
  level:
    org:
      mongodb:
        driver: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8082