spring:
  cloud:
    discovery:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user: admin
    packages:
      trust-all: true
    close-timeout: 10s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8082