spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: lb:http://USER
          predicates:
            - Path=/api/v1/user/**
        - id: notification
          uri: lb:http://NOTIFICATION
          predicates:
            - Path=/api/v1/notification/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
server:
  port: 8080
