spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eureka-db
      database: eureka-db
    cloud:
      discovery:
        enabled: true
  kafka:
    bootstrapServers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

server:
  port: 8082